# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13f25164a85c2017c7109e8004051cd25ac99dadecd042f9b0f86f8b04f6782950534991f7bb9ddad1c792ca287dd4c41677868666d61cb4e5e2c163bf42d27c

test:
  secret_key_base: 5c0bcea5278db41015f0449c951a8eef5632338deab1483b4213e7c8360dda713133ddbb1706945ea7ecde697a11505252c0f271632a049ca8fb64e0dfed158e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
